test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,8 +18,16 @@ jobs:
               name: Install specific packages
               command: npm install concurrently wait-on
           - run:
-              name: run-e2e-tests
-              command: npm run circleci-run
+              name: Run e2e tests
+              command: |
+                npm run circleci-run
+                if [ $? -eq 0 ]; then
+                  echo "Tests passed! Exiting job."
+                  exit 0
+                else
+                  echo "Tests failed. Exiting with error."
+                  exit 1
+                fi
           # - run:
           #     name: Stop any lingering processes
           #     command: |
